DROP TABLE states;

CREATE TABLE states (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    json VARCHAR NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    group_id INTEGER,
    FOREIGN KEY(group_id) REFERENCES groups(id)
);
