CREATE TABLE devices (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE states (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    json VARCHAR NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    device_id INTEGER,
    FOREIGN KEY(device_id) REFERENCES devices(id)
);
