name: Run deploy

on: 
  push:
    branches: main
    paths: python_example_project

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Build CLI
        working-directory: ./cli
        run: cargo install --path .

      - name: Run up
        working-directory: ./python_example_project
        run: ovejas up --env test-env
